config/routes.rb
Rails.application.routes.draw do
  get '/stocks/:ticker_symbol', to: 'stocks#show'
  get '/stocks/stock/:ticker_symbol', to: 'stocks#stock'
  resources :stocks
  resources :stock_prices
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  validates_uniqueness_of :ticker_symbol
  attr_accessor :price
  attr_accessor :previous_close
  attr_accessor :history

  def self.with_stock_ticker_ws(ticker_symbol)
    stock = Stock.where(ticker_symbol: ticker_symbol).take

    ticker_symbol =  stock.ticker_symbol
    response = get_prices_from_ws(ticker_symbol)
    populate_from_web_service(stock, response)
    add_history_from_web_service(stock)
  end

  def self.all_with_ws_prices
    stocks = Stock.all
    ticker_symbols =  stocks.collect {|stock| stock.ticker_symbol}.join(',')

    response = get_prices_from_ws(ticker_symbols)
    stocks.collect do |stock|
      populate_from_web_service(stock, response)
  	end
  end

  def self.get_prices_from_ws (ticker_symbols)
    response = RestClient.get "http://download.finance.yahoo.com/d/quotes.csv?s=%40%5EDJI,#{ticker_symbols}&f=nsl1op&e=.csv"
  end

  def self.populate_from_web_service(stock, ws_response)
    row = ws_response.each_line.collect do |line|
      line.gsub("\r\n",'').gsub('"', '').split(',')
    end

    filtered_row = row.select { |line| line[line.size - 4] == stock.ticker_symbol }.first

    stock.price = filtered_row[filtered_row.size - 3].to_f
    stock.previous_close = filtered_row[filtered_row.size - 1].to_f
    stock
  end 

  def self.add_history_from_web_service(stock)
    response = RestClient.get "http://ichart.yahoo.com/table.csv?s=#{stock.ticker_symbol}&a=5&b=1&c=2014"
    stock.history = []
    response.each_line.collect do |line|
      stock.history.push(line.gsub("\n", '').split(','))
    end
    stock.history.shift
    stock
  end


  def price_change
    ((@price - @previous_close) * 100.0).round / 100.0
  end


  
end

app/models/stock_price.rb
class StockPrice < ActiveRecord::Base

	def self.find_current_prices
		response = RestClient.get "http://download.finance.yahoo.com/d/quotes.csv?s=%40%5EDJI,#{ticker_symbols}&f=nsl1op&e=.csv"
	end

	def self.get_all_prices_from_stock(stock)
		ticker_symbol = stock.ticker_symbol

		stock_prices = StockPrice.all.where(stock: stock)
		

    	response = RestClient.get "http://download.finance.yahoo.com/d/quotes.csv?s=%40%5EDJI,#{ticker_symbols}&f=nsl1op&e=.csv"
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/stock_prices_controller.rb
class StockPricesController < ApplicationController
  before_action :set_stock_price, only: [:show, :edit, :update, :destroy]

  # GET /stock_prices
  # GET /stock_prices.json
  def index
    @stock_prices = StockPrice.all_with_prices
  end

  # GET /stock_prices/1
  # GET /stock_prices/1.json
  def show
  end

  # GET /stock_prices/new
  def new
    @stock_price = StockPrice.new
  end

  # GET /stock_prices/1/edit
  def edit
  end

  # POST /stock_prices
  # POST /stock_prices.json
  def create
    @stock_price = StockPrice.new(stock_price_params)

    respond_to do |format|
      if @stock_price.save
        format.html { redirect_to @stock_price, notice: 'Stock price was successfully created.' }
        format.json { render :show, status: :created, location: @stock_price }
      else
        format.html { render :new }
        format.json { render json: @stock_price.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stock_prices/1
  # PATCH/PUT /stock_prices/1.json
  def update
    respond_to do |format|
      if @stock_price.update(stock_price_params)
        format.html { redirect_to @stock_price, notice: 'Stock price was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock_price }
      else
        format.html { render :edit }
        format.json { render json: @stock_price.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stock_prices/1
  # DELETE /stock_prices/1.json
  def destroy
    @stock_price.destroy
    respond_to do |format|
      format.html { redirect_to stock_prices_url, notice: 'Stock price was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock_price
      @stock_price = StockPrice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_price_params
      params.require(:stock_price).permit(:stock, :date, :open, :high, :close, :volume, :adj_close)
    end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def index
  	@stocks = Stock.all_with_ws_prices
  	@messages = []
  	@open_positions = []
  	@closed_positions = []
  	@stocks_to_check = []
  end

  def create
  	@stock = Stock.create(stock_params)
  	if @stock.save
  		respond_to do |format|
  			format.html { render text: "please submit as json" }
  			format.json { render text: "created stock #{@stock.ticker_symbol}" }
 		  end
  	end
  end

  def show
    @ticker_symbol = params[:ticker_symbol]
  end

  def stock
    @stock = Stock.with_stock_ticker_ws(params[:ticker_symbol])
  end

  private

  def stock_params
  	params.require(:stock).permit(:ticker_symbol)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stock_helper.rb
module StockHelper
end

app/helpers/stock_prices_helper.rb
module StockPricesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="myApp">
<head>
  <title>StockAnalysis</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'nv.d3.js', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'nv.d3.css', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body data-no-turbolink>

<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Dashboard", stocks_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class='container'>
<%= yield %>
</div>

</body>
</html>

app/views/stocks/index.html.erb
<h1>Dashboard</h1>

<div class='row'>
  <div class='col-md-3' ng-controller='WatchingStocksController'>
  	<h3>Watching Stocks</h3>
    <ul class="list-group">
    	<li class='list-group-item' ng-repeat="stock in watchingStocks">
         <a href='/stocks/{{ stock.ticker_symbol }}'>{{ stock.ticker_symbol }}</a> 
         <span ng-if='stock.price > stock.previous_close' style='color:green;'>
           ${{ stock.price }} (<span ng-if='stock.price_change > 0.0'>+</span>{{ stock.price_change }})
         </span>
         <span ng-if='stock.price == stock.previous_close'>
           ${{ stock.price }} (<span ng-if='stock.price_change > 0.0'>+</span>{{ stock.price_change }})
         </span>
         <span ng-if='stock.price < stock.previous_close' style='color:red;'>
           ${{ stock.price }} (<span ng-if='stock.price_change > 0.0'>+</span>{{ stock.price_change }})
         </span>
      </li>

    <li class='list-group-item'>
      <input type="text" ng-model="newStock" />
      <a href='#' ng-click="add()">
        <span class='glyphicon glyphicon-plus' aria-hidden='true'>
        </span>
      </a>
    </li>

    <h3>Interesting Today</h3>
    <ul class="list-group">
    	<li class="list-group-item">
        </li>
    <% @stocks_to_check.each do |stock|  %>
      <li class="list-group-item">
        <%= stock.ticker_symbol %>
      </li>
    <% end %>
    </ul>
  </div>
  <div class='col-md-6'>
  	<h3>App Messages</h3>
  	<ul class="list-group">
  		<li class="list-group-item">
  			message
        </li>
  	<% @messages.each do |message| %>
	    <li class="list-group-item">
  			<%= message %>
        </li>
  	<% end %>	
    </ul>
  </div>
  <div class='col-md-2'>
  	<h3>Current Positions</h3>

  	<ul class="list-group">
  		<li class="list-group-item">
  			current message
        </li>
  	<% @open_positions.each do |open_position| %>

  	<% end %>
    </ul>
  	<br />

	<h3>History</h3>

  	<ul class="list-group">
  		<li class="list-group-item">
  			history message
        </li>
	<% @closed_positions.each do |closed_position| %>

	<% end %>
	</ul>
  </div>
</div>

app/views/stocks/show.html.erb
<h1 id='stockName'>
	<%= @ticker_symbol %>
</h1>

<style>
  .axis path, .axis line {
  	fill: none;
  	stroke: #777;
  	shape-rendering: crispEdges;
  }
</style>


<h3>Chart</h3>
<div ng-controller='StockChartController' ng-init="init('<%= @ticker_symbol %>')">
	<svg id='visualization' width="1000" height="500"></svg>
	<ul>
		<li>
		     
		      <a href='#' ng-click="add()">
		        Simple Moving Average<span class='glyphicon glyphicon-plus' aria-hidden='true'>
		        </span>
		      </a>
		      <input type="text" ng-model="numDays" />
		      <input id='colorpicker' ng-model='lineColor' />
		</li>
	</ul>
</div>

<script type='text/javascript'>
$(document).ready(function(){
	$('#colorpicker').colorpicker();
});

</script>

	


<h3>Messages</h3>